SELECT * FROM PERSON_TBL;

SELECT * FROM GENDER_TBL;

DELETE FROM GENDER_TBL WHERE ID = 1;


ALTER TABLE PERSON_TBL
ADD AGE INT;

ALTER TABLE PERSON_TBL
ADD CONSTRAINT CK_PERSON_TBL_AGE
CHECK (AGE > 18 AND AGE < 80);

UPDATE PERSON_TBL 
SET AGE = 42
WHERE ID = 7;

ALTER TABLE PERSON_TBL
ADD CONSTRAINT UQ_PERSON_TBL_EMAIL 
UNIQUE (EMAIL);

SELECT * FROM PERSON_TBL;

SELECT * FROM GENDER_TBL;

SELECT NAME, EMAIL, GENDER, AGE
FROM PERSON_TBL
LEFT OUTER JOIN GENDER_TBL
ON PERSON_TBL.GENDER_ID = GENDER_TBL.ID;

ALTER TABLE PERSON_TBL
ADD MANAGER_ID INT;

UPDATE PERSON_TBL
SET MANAGER_ID = 3
WHERE ID = 8;

SELECT E.NAME AS EMPLOYEE, M.NAME AS MANAGER
FROM PERSON_TBL M 
 RIGHT JOIN PERSON_TBL E
ON M.ID = E.MANAGER_ID;

SELECT E.NAME AS EMPLOYEE, CASE WHEN M.NAME IS NULL THEN 'THE CEO' ELSE M.NAME END AS MANAGER
FROM PERSON_TBL M 
 RIGHT JOIN PERSON_TBL E
ON M.ID = E.MANAGER_ID;