INSERT INTO PERSON_TBL
VALUES (1, 'JUDE', 'JUDE@MAIL.COM',2),
(2, 'MARY', 'MARY@M.COM',2),
(3, 'MARTIN', 'MARTIN@M.COM',1),
(4, 'ROB', 'ROB@R.COM',1),
(5,'MAY', 'MAY@M.COM',2),
(6,'KRISTY', 'KRISTY@K.COM',2)

INSERT INTO PERSON_TBL (ID, NAME, EMAIL)
VALUES
(7, 'JOHNNY', 'JOHNNY@J.COM');

SELECT * FROM PERSON_TBL;

SELECT * FROM GENDER_TBL;

INSERT INTO GENDER_TBL
VALUES (3, 'U');

UPDATE PERSON_TBL
SET GENDER_ID = 1
WHERE ID = 7;

ALTER TABLE PERSON_TBL
ADD CONSTRAINT DFLT_PERSONTBL_GENDERID
DEFAULT 3 FOR GENDER_ID;

ALTER TABLE PERSON_TBL
ALTER COLUMN NAME VARCHAR (25) NOT NULL;

INSERT INTO PERSON_TBL (ID, NAME, EMAIL)
VALUES
(8, 'KENNY', 'KENNY@J.COM');