INSERT INTO STUDENT_TBL
VALUES (2, 'MARY', 'MAGDA', '1122 JEFFS STREET', 'F'),
 (4, 'JOHN', 'JUDAH', '5345 KELLYS STREET', 'M'),
 (5, 'FRANCISCA', 'LOPEZ', '1123 JEFFS STREET', 'F'),
 (4, 'JOHN', 'JUDAH', '5345 KELLYS STREET', 'M')

 SELECT * FROM STUDENT_TBL;

 SELECT COUNT(STUDENT_ID) AS FREQUENCY, STUDENT_ID, FIRST_NAME, LAST_NAME, ADDRESS, GENDER 
 FROM STUDENT_TBL
 GROUP BY STUDENT_ID, FIRST_NAME, LAST_NAME, ADDRESS, GENDER
 HAVING COUNT(STUDENT_ID) > 1
  
INSERT INTO STUDENT_TBL
VALUES (6, 'BRAD', 'PITT', '1231 COOPER STREET','M'),
(7, 'OCONNER', 'BRIAN', '3061 KELLYS STREET', 'M'),
(2, 'MARY', 'MAGDA', '1122 JEFFS STREET', 'F'),
(5, 'FRANCISCA', 'LOPEZ', '1123 JEFFS STREET', 'F'),
(8, 'BOB', 'MALEY', '2016, SHUFFLE DRIVE', 'M'),
(2, 'MARY', 'MAGDA', '1122 JEFFS STREET', 'F');

SELECT * FROM STUDENT_TBL;

SELECT COUNT(STUDENT_ID) AS FREQUENCY, STUDENT_ID, FIRST_NAME, LAST_NAME, ADDRESS, GENDER
FROM STUDENT_TBL
GROUP BY STUDENT_ID, FIRST_NAME, LAST_NAME, ADDRESS, GENDER
HAVING COUNT(STUDENT_ID) > 1 


